//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavisApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NavisworksParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavisworksParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavisApp.Properties.NavisworksParameters", typeof(NavisworksParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim executado.
        /// </summary>
        internal static string ActualEndParameter {
            get {
                return ResourceManager.GetString("ActualEndParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início executado.
        /// </summary>
        internal static string ActualStartParameter {
            get {
                return ResourceManager.GetString("ActualStartParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipamentos.
        /// </summary>
        internal static string EquipmentCost {
            get {
                return ResourceManager.GetString("EquipmentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mão-de-obra.
        /// </summary>
        internal static string LaborCost {
            get {
                return ResourceManager.GetString("LaborCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string MaterialCost {
            get {
                return ResourceManager.GetString("MaterialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim planejado.
        /// </summary>
        internal static string PlannedEndParameter {
            get {
                return ResourceManager.GetString("PlannedEndParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início planejado.
        /// </summary>
        internal static string PlannedStartParameter {
            get {
                return ResourceManager.GetString("PlannedStartParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progresso.
        /// </summary>
        internal static string Provided_Progress {
            get {
                return ResourceManager.GetString("Provided Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terceirizada.
        /// </summary>
        internal static string SubcontractorCost {
            get {
                return ResourceManager.GetString("SubcontractorCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custo total.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
    }
}
